services:
  react_app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/react_app"
      - "/react_app/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
